export const STARTER_SET_ACTORS = [
  {
    name: "Rad Rocky",
    type: "npc",
    category: "notable",
    xp: 34,
    level: 2,
    token: "systems/fallout/assets/tokens/npc.webp",
    special: { str: 7, per: 6, end: 7, cha: 5, int: 6, agi: 7, luc: 5 },
    derived: { hp: 14, initiative: 15, defense: 1, carryWeight: 220, meleeBonus: 1, luck: 3, wealth: 1 },
    bodyResist: {
      physical: { armL: 1, armR: 1, torso: 1 },
      energy: { armL: 1, armR: 1, torso: 1 },
    },
    skills: [
      { name: "Explosives", value: 2, tag: true, defaultAttribute: "per" },
      { name: "Sneak", value: 1, defaultAttribute: "agi" },
      { name: "Medicine", value: 1, defaultAttribute: "int" },
      { name: "Survival", value: 1, defaultAttribute: "end" },
      { name: "Melee Weapons", value: 2, tag: true, defaultAttribute: "str" },
      { name: "Throwing", value: 1, defaultAttribute: "agi" },
      { name: "Repair", value: 1, defaultAttribute: "int" },
      { name: "Unarmed", value: 2, defaultAttribute: "str" },
      { name: "Small Guns", value: 2, tag: true, defaultAttribute: "agi" },
    ],
    items: [
      { kind: "apparel", name: "Road Leathers", physical: 1, energy: 1, locations: ["armL", "armR", "torso"], equipped: true },
      { kind: "weapon", name: "Tire Iron", attribute: "str", skill: "meleeWeapons", weaponType: "meleeWeapons", damage: 3, damageType: "physical", range: "close", melee: true },
      { kind: "weapon", name: "Sharpshooter's Pipe Revolver", attribute: "agi", skill: "smallGuns", weaponType: "smallGuns", damage: 3, damageType: "physical", range: "close", fireRate: 1, qualities: ["close_quarters", "unreliable"], damageEffects: [{ key: "piercing_x", value: 1 }] },
      { kind: "ability", name: "Let Rip", description: "Once per combat, Rad Rocky may let rip with a volley from his pipe revolver, adding its Fire Rate to the weapon's damage for a single attack." },
      { kind: "ability", name: "Turn and Run", description: "If Rad Rocky is the only remaining enemy, he attempts to flee the battle." },
    ],
    biography: "Leader of the opening Gunner raider ambush outside Vault 95. He opens aggressively, then bolts if his gang is dropped around him.",
  },
  {
    name: "Raider",
    type: "npc",
    category: "normal",
    xp: 17,
    level: 2,
    token: "systems/fallout/assets/tokens/npc.webp",
    special: { str: 6, per: 5, end: 6, cha: 4, int: 5, agi: 6, luc: 4 },
    derived: { hp: 8, initiative: 11, defense: 1, carryWeight: 210, meleeBonus: 0, wealth: 1 },
    bodyResist: {
      physical: { armL: 1, armR: 1, torso: 1 },
      energy: { armL: 1, armR: 1, torso: 1 },
    },
    skills: [
      { name: "Medicine", value: 1, defaultAttribute: "int" },
      { name: "Sneak", value: 1, defaultAttribute: "agi" },
      { name: "Melee Weapons", value: 2, tag: true, defaultAttribute: "str" },
      { name: "Survival", value: 1, defaultAttribute: "end" },
      { name: "Repair", value: 1, defaultAttribute: "int" },
      { name: "Throwing", value: 1, defaultAttribute: "agi" },
      { name: "Small Guns", value: 2, tag: true, defaultAttribute: "agi" },
      { name: "Unarmed", value: 2, defaultAttribute: "str" },
    ],
    items: [
      { kind: "apparel", name: "Road Leathers", physical: 1, energy: 1, locations: ["armL", "armR", "torso"], equipped: true },
      { kind: "weapon", name: "Tire Iron", attribute: "str", skill: "meleeWeapons", weaponType: "meleeWeapons", damage: 4, damageType: "physical", range: "close", melee: true },
      { kind: "weapon", name: "Pipe Gun", attribute: "agi", skill: "smallGuns", weaponType: "smallGuns", damage: 3, damageType: "physical", range: "close", fireRate: 2, qualities: ["close_quarters", "unreliable"] },
      { kind: "ability", name: "Let Rip", description: "Once per combat, the raider may let rip with a volley from their pipe gun, adding its Fire Rate to the weapon's damage for a single attack." },
    ],
    biography: "Generic Gunner-style raider used during the Vault 95 opening fight.",
  },
  {
    name: "Doctor Rast (Vault Escort)",
    type: "npc",
    category: "notable",
    xp: 62,
    level: 4,
    token: "systems/fallout/assets/tokens/npc.webp",
    special: { str: 6, per: 8, end: 6, cha: 6, int: 8, agi: 7, luc: 5 },
    derived: { hp: 15, initiative: 17, defense: 1, carryWeight: 200, meleeBonus: 0, luck: 3, wealth: 4 },
    bodyResist: {
      physical: { armL: 3, armR: 3, torso: 3 },
      energy: { armL: 3, armR: 3, torso: 3 },
    },
    immunities: { poison: true, radiation: true },
    skills: [
      { name: "Energy Weapons", value: 3, tag: true, defaultAttribute: "per" },
      { name: "Small Guns", value: 2, defaultAttribute: "agi" },
      { name: "Lockpick", value: 2, defaultAttribute: "per" },
      { name: "Sneak", value: 1, defaultAttribute: "agi" },
      { name: "Medicine", value: 4, tag: true, defaultAttribute: "int" },
      { name: "Speech", value: 3, tag: true, defaultAttribute: "cha" },
      { name: "Science", value: 2, defaultAttribute: "int" },
    ],
    items: [
      { kind: "apparel", name: "Lab Coat with Ballistic Weave", physical: 3, energy: 3, locations: ["armL", "armR", "torso"], equipped: true },
      { kind: "weapon", name: "Boosted Focused Institute Laser Rifle", attribute: "per", skill: "energyWeapons", weaponType: "energyWeapons", damage: 4, damageType: "energy", range: "medium", fireRate: 2, qualities: ["concealed", "two_handed"], damageEffects: [{ key: "burst", value: 1 }] },
      { kind: "ability", name: "Robot", description: "Rast is immune to starvation, thirst, suffocation, poison, and radiation, but does not heal naturally and must be repaired instead of treated with Medicine." },
      { kind: "ability", name: "Advanced Synth", description: "Rast appears human until his synth component is recovered after death. His synthetic body boosts his STR, PER, INT, and defensive resilience." },
      { kind: "ability", name: "Let Rip", description: "Once per combat, Doctor Rast may add his laser rifle's Fire Rate to the weapon's damage and use Burst without spending extra ammo." },
      { kind: "ability", name: "Stimpak Supply", description: "Rast carries enough Stimpaks to keep the party patched up through the adventure." },
      { kind: "ability", name: "Hidden Armament", description: "Rast's specially modified institute laser weapon is built to be concealed on an infiltrator." },
    ],
    biography: "The apparently helpful doctor shadowing the party through Vault 95. He pushes the PCs toward Diamond City while keeping his Institute mission hidden.",
  },
  {
    name: "Doctor Rast (Finale)",
    type: "npc",
    category: "notable",
    xp: 62,
    level: 4,
    token: "systems/fallout/assets/tokens/npc.webp",
    special: { str: 6, per: 8, end: 6, cha: 6, int: 8, agi: 7, luc: 5 },
    derived: { hp: 15, initiative: 17, defense: 1, carryWeight: 200, meleeBonus: 0, luck: 3, wealth: 4 },
    bodyResist: {
      physical: { armL: 3, armR: 3, torso: 3 },
      energy: { armL: 3, armR: 3, torso: 3 },
    },
    immunities: { poison: true, radiation: true },
    skills: [
      { name: "Energy Weapons", value: 3, tag: true, defaultAttribute: "per" },
      { name: "Repair", value: 1, defaultAttribute: "int" },
      { name: "Medicine", value: 4, tag: true, defaultAttribute: "int" },
      { name: "Small Guns", value: 1, defaultAttribute: "agi" },
      { name: "Melee Weapons", value: 3, tag: true, defaultAttribute: "str" },
      { name: "Speech", value: 1, defaultAttribute: "cha" },
    ],
    items: [
      { kind: "apparel", name: "Lab Coat with Ballistic Weave", physical: 3, energy: 3, locations: ["armL", "armR", "torso"], equipped: true },
      { kind: "weapon", name: "Boosted Focused Institute Laser Rifle", attribute: "per", skill: "energyWeapons", weaponType: "energyWeapons", damage: 4, damageType: "energy", range: "medium", fireRate: 2, qualities: ["concealed", "two_handed"], damageEffects: [{ key: "burst", value: 1 }] },
      { kind: "ability", name: "Robot", description: "Rast is immune to starvation, thirst, suffocation, poison, and radiation, but does not heal naturally and must be repaired instead of treated with Medicine." },
      { kind: "ability", name: "Advanced Synth", description: "Rast appears human until his synth component is recovered after death. His synthetic body boosts his STR, PER, INT, and defensive resilience." },
      { kind: "ability", name: "Let Rip", description: "Once per combat, Doctor Rast may add his laser rifle's Fire Rate to the weapon's damage and use Burst without spending extra ammo." },
      { kind: "ability", name: "Stimpak Supply", description: "Rast still carries enough Stimpaks to keep allies patched up even in the finale." },
      { kind: "ability", name: "Hidden Armament", description: "Rast's specially modified institute laser weapon is built to be concealed on an infiltrator." },
    ],
    biography: "Late-adventure betrayal version of Rast, using the altered skill mix from the final showdown pages.",
  },
  {
    name: "Mister Gutsy",
    type: "robot",
    category: "notable",
    xp: 104,
    level: 7,
    token: "systems/fallout/assets/tokens/robot.webp",
    special: { str: 6, per: 8, end: 6, cha: 6, int: 8, agi: 7, luc: 5 },
    derived: { hp: 18, initiative: 17, defense: 1, carryWeight: 150, meleeBonus: 0, luck: 3 },
    bodyResist: {
      physical: { head: 2, torso: 2, armL: 2, armR: 2, legL: 2, legR: 2 },
      energy: { head: 2, torso: 2, armL: 2, armR: 2, legL: 2, legR: 2 },
    },
    immunities: { poison: true, radiation: true },
    skills: [
      { name: "Energy Weapons", value: 4, tag: true, defaultAttribute: "per" },
      { name: "Small Guns", value: 4, tag: true, defaultAttribute: "agi" },
      { name: "Melee Weapons", value: 3, tag: true, defaultAttribute: "str" },
      { name: "Speech", value: 1, defaultAttribute: "cha" },
      { name: "Repair", value: 1, defaultAttribute: "int" },
    ],
    items: [
      { kind: "weapon", name: "Pincer", attribute: "str", skill: "meleeWeapons", weaponType: "meleeWeapons", damage: 4, damageType: "physical", range: "close", melee: true, natural: true },
      { kind: "weapon", name: "10mm Auto Pistol", attribute: "agi", skill: "smallGuns", weaponType: "smallGuns", damage: 5, damageType: "physical", range: "close", fireRate: 4, qualities: ["close_quarters", "reliable"], damageEffects: [{ key: "burst", value: 1 }] },
      { kind: "weapon", name: "Flamer", attribute: "per", skill: "energyWeapons", weaponType: "energyWeapons", damage: 3, damageType: "energy", range: "close", fireRate: 1, damageEffects: [{ key: "persistent", value: 1 }] },
      { kind: "ability", name: "Robot", description: "Immune to starvation, thirst, suffocation, poison, and radiation; repairs instead of medical healing." },
      { kind: "ability", name: "Immune to Poison", description: "The Mister Gutsy reduces poison damage to 0 and cannot suffer poison effects." },
      { kind: "ability", name: "Immune to Radiation", description: "The Mister Gutsy reduces radiation damage to 0 and cannot suffer radiation effects." },
      { kind: "ability", name: "Immune to Disease", description: "The Mister Gutsy ignores the effects of disease." },
      { kind: "ability", name: "Mister Handy", description: "360° senses, airborne movement, and improved detection for visual and olfactory PER tests." },
      { kind: "ability", name: "Mister Gutsy", description: "Built for war, with boosted attacks and military intimidation against those outside formal uniforms." },
    ],
    biography: "Vault 95 patrol robot and possible unexpected ally if a Mister Handy PC talks it down.",
  },
  {
    name: "Dog",
    type: "creature",
    category: "normal",
    xp: 24,
    level: 3,
    token: "systems/fallout/assets/tokens/creature.webp",
    creature: { body: 5, mind: 5, melee: 3, guns: 0, other: 2 },
    derived: { hp: 8, initiative: 10, defense: 1 },
    creatureResist: { physical: 0, energy: 0, radiation: 0, poison: 0 },
    items: [
      { kind: "weapon", name: "Bite", creatureAttribute: "body", creatureSkill: "melee", weaponType: "unarmed", damage: 4, damageType: "physical", range: "close", melee: true, natural: true },
      { kind: "ability", name: "Keen Senses", description: "One or more of the dog's senses are especially keen; reduce the difficulty of PER tests by 1 and allow unusual detection opportunities." },
    ],
    biography: "The starving stray from the campfire night. It can become a recurring ally if the party earns its loyalty.",
  },
  {
    name: "Feral Ghoul",
    type: "creature",
    category: "normal",
    xp: 10,
    level: 3,
    token: "systems/fallout/assets/tokens/creature.webp",
    creature: { body: 5, mind: 5, melee: 3, guns: 0, other: 2 },
    derived: { hp: 8, initiative: 10, defense: 1 },
    creatureResist: { physical: 0, energy: 0, radiation: 0, poison: 0 },
    immunities: { poison: true, radiation: true },
    items: [
      { kind: "weapon", name: "Unarmed", creatureAttribute: "body", creatureSkill: "melee", weaponType: "unarmed", damage: 3, damageType: "physical", range: "close", melee: true, natural: true, damageEffects: [{ key: "radioactive", value: 1 }] },
      { kind: "ability", name: "Immune to Radiation", description: "The feral ghoul reduces radiation damage suffered to 0 and cannot suffer radiation effects." },
      { kind: "ability", name: "Immune to Poison", description: "The feral ghoul reduces poison damage suffered to 0 and cannot suffer poison effects." },
      { kind: "ability", name: "Feral", description: "Driven entirely by instinct; it cannot be reasoned with and charges the nearest viable prey or disturbance." },
      { kind: "ability", name: "Ghoul", description: "Radiation heals the ghoul, restoring 1 HP for every 3 radiation damage inflicted on it." },
      { kind: "ability", name: "Play Dead", description: "A prone feral ghoul can be difficult to distinguish from a corpse until it springs its ambush." },
    ],
    biography: "Warehouse encounter ghoul profile for the family gone fully feral.",
  },
  {
    name: "Mirelurk Hatchling",
    type: "creature",
    category: "normal",
    xp: 10,
    level: 1,
    token: "systems/fallout/assets/tokens/creature.webp",
    creature: { body: 4, mind: 4, melee: 1, guns: 0, other: 1 },
    derived: { hp: 5, initiative: 8, defense: 2 },
    creatureResist: { physical: 0, energy: 0, radiation: 0, poison: 0 },
    immunities: { radiation: true },
    items: [
      { kind: "weapon", name: "Pincers", creatureAttribute: "body", creatureSkill: "melee", weaponType: "meleeWeapons", damage: 3, damageType: "physical", range: "close", melee: true, natural: true },
      { kind: "ability", name: "Immune to Radiation", description: "The hatchling reduces radiation damage to 0 and cannot suffer radiation effects." },
      { kind: "ability", name: "Little", description: "Smaller than most targets, the hatchling gains higher Defense but is slain by any hit that inflicts an injury." },
      { kind: "ability", name: "Aquatic", description: "The hatchling can swim and remain underwater indefinitely without suffering attack or movement penalties." },
    ],
    biography: "Small mirelurks that skitter through the Boston sewer sequence and can reinforce the queen's nest.",
  },
  {
    name: "Mirelurk Queen, Wounded",
    type: "creature",
    category: "mighty",
    xp: 67,
    level: 9,
    token: "systems/fallout/assets/tokens/creature.webp",
    creature: { body: 12, mind: 6, melee: 3, guns: 0, other: 3 },
    derived: { hp: 28, initiative: 18, defense: 1 },
    creatureResist: { physical: 5, energy: 3, radiation: 0, poison: 9 },
    creatureLocationText: {
      physical: "Torso, Legs, Arms 5; Face 2",
      energy: "All 3",
      poison: "All 9",
      radiation: "Immune",
    },
    immunities: { radiation: true },
    items: [
      { kind: "weapon", name: "Pincers", creatureAttribute: "body", creatureSkill: "melee", weaponType: "meleeWeapons", damage: 7, damageType: "physical", range: "close", melee: true, natural: true, damageEffects: [{ key: "vicious", value: 1 }] },
      { kind: "weapon", name: "Acid Spray", creatureAttribute: "body", creatureSkill: "melee", weaponType: "unarmed", damage: 5, damageType: "radiation", range: "close", melee: true, natural: true, damageEffects: [{ key: "piercing_x", value: 1 }] },
      { kind: "ability", name: "Hatchling Spawn", description: "Once per round, the GM may spend 4 AP as a major action to spawn four mirelurk hatchlings instead of attacking." },
      { kind: "ability", name: "Immune to Radiation", description: "The wounded queen reduces radiation damage to 0 and cannot suffer radiation effects." },
      { kind: "ability", name: "Immune to Fear", description: "The wounded queen cannot be intimidated or threatened." },
      { kind: "ability", name: "Small Weak Point", description: "The queen's face is a small weak point treated as Defense 2 when specifically targeted." },
      { kind: "ability", name: "Aquatic", description: "The queen can swim and remain underwater indefinitely without suffering attack or movement penalties." },
      { kind: "ability", name: "Big", description: "The queen towers over most characters, with extra HP and a higher threshold before suffering a critical hit." },
    ],
    biography: "Boss threat in the sewer nest. The published stat block begins wounded at 28/50 HP and can spend AP to spawn hatchlings.",
  },
  {
    name: "Super Mutant",
    type: "npc",
    category: "normal",
    xp: 38,
    level: 5,
    token: "systems/fallout/assets/tokens/npc.webp",
    special: { str: 9, per: 5, end: 7, cha: 4, int: 4, agi: 5, luc: 4 },
    derived: { hp: 12, initiative: 10, defense: 1, carryWeight: 240, meleeBonus: 2 },
    bodyResist: {
      physical: { head: 2, torso: 2, armL: 2, armR: 2, legL: 2, legR: 2 },
      energy: { head: 2, torso: 2, armL: 2, armR: 2, legL: 2, legR: 2 },
    },
    immunities: { poison: true, radiation: true },
    skills: [
      { name: "Big Guns", value: 1, defaultAttribute: "end" },
      { name: "Survival", value: 3, tag: true, defaultAttribute: "end" },
      { name: "Melee Weapons", value: 4, tag: true, defaultAttribute: "str" },
      { name: "Unarmed", value: 2, defaultAttribute: "str" },
      { name: "Small Guns", value: 3, defaultAttribute: "agi" },
    ],
    items: [
      { kind: "weapon", name: "Board", attribute: "str", skill: "meleeWeapons", weaponType: "meleeWeapons", damage: 6, damageType: "physical", range: "close", melee: true, qualities: ["two_handed"] },
      { kind: "weapon", name: "Pipe Bolt-Action Rifle", attribute: "agi", skill: "smallGuns", weaponType: "smallGuns", damage: 5, damageType: "physical", range: "medium", fireRate: 0, qualities: ["two_handed"], damageEffects: [{ key: "piercing_x", value: 1 }] },
      { kind: "ability", name: "Barbarian", description: "+2 to Physical and Energy damage resistances (already included in the stat line)." },
      { kind: "ability", name: "Immune to Radiation", description: "The super mutant reduces radiation damage suffered to 0 and cannot suffer radiation effects." },
      { kind: "ability", name: "Immune to Poison", description: "The super mutant reduces poison damage suffered to 0 and cannot suffer poison effects." },
    ],
    biography: "Street ambush mutant profile just outside Diamond City.",
  },
  {
    name: "Diamond City Security",
    type: "npc",
    category: "normal",
    xp: 45,
    level: 6,
    token: "systems/fallout/assets/tokens/npc.webp",
    special: { str: 6, per: 7, end: 6, cha: 5, int: 4, agi: 6, luc: 4 },
    derived: { hp: 12, initiative: 13, defense: 1, carryWeight: 210, meleeBonus: 0, wealth: 2 },
    bodyResist: {
      physical: { head: 1, armL: 2, armR: 2, torso: 2 },
      energy: { head: 1, armL: 1, armR: 1, torso: 2 },
    },
    skills: [
      { name: "Athletics", value: 1, defaultAttribute: "str" },
      { name: "Small Guns", value: 3, tag: true, defaultAttribute: "agi" },
      { name: "Big Guns", value: 1, defaultAttribute: "end" },
      { name: "Speech", value: 2, tag: true, defaultAttribute: "cha" },
      { name: "Energy Weapons", value: 2, defaultAttribute: "per" },
      { name: "Survival", value: 1, defaultAttribute: "end" },
      { name: "Medicine", value: 1, defaultAttribute: "int" },
      { name: "Unarmed", value: 2, defaultAttribute: "str" },
      { name: "Melee Weapons", value: 3, tag: true, defaultAttribute: "str" },
    ],
    items: [
      { kind: "apparel", name: "Diamond City Guard Gear", physical: 2, energy: 2, locations: ["head", "armL", "armR", "torso"], equipped: true },
      { kind: "weapon", name: "Baseball Bat", attribute: "str", skill: "meleeWeapons", weaponType: "meleeWeapons", damage: 4, damageType: "physical", range: "close", melee: true, qualities: ["two_handed"] },
      { kind: "weapon", name: "Auto Pipe Rifle", attribute: "agi", skill: "smallGuns", weaponType: "smallGuns", damage: 2, damageType: "physical", range: "medium", fireRate: 4, qualities: ["two_handed", "unreliable"], damageEffects: [{ key: "burst", value: 1 }] },
      { kind: "ability", name: "Let Rip", description: "Once per combat, the guard may add the auto pipe rifle's Fire Rate to the weapon's damage and use Burst without spending extra ammo." },
    ],
    biography: "Baseline Diamond City guard profile for crowd control, reinforcements, and the finale rescue option.",
  },
  {
    name: "Commonwealth Merchant",
    type: "npc",
    category: "notable",
    xp: 62,
    level: 4,
    token: "systems/fallout/assets/tokens/npc.webp",
    special: { str: 5, per: 6, end: 6, cha: 9, int: 8, agi: 5, luc: 5 },
    derived: { hp: 15, initiative: 12, defense: 1, carryWeight: 210, meleeBonus: 0, wealth: 6 },
    bodyResist: {
      physical: { armL: 1, armR: 1, legL: 1, legR: 1, torso: 1 },
      energy: { armL: 2, armR: 2, legL: 2, legR: 2, torso: 2 },
    },
    skills: [
      { name: "Barter", value: 4, tag: true, defaultAttribute: "cha" },
      { name: "Small Guns", value: 3, tag: true, defaultAttribute: "agi" },
      { name: "Lockpick", value: 1, defaultAttribute: "per" },
      { name: "Speech", value: 2, tag: true, defaultAttribute: "cha" },
      { name: "Melee Weapons", value: 2, defaultAttribute: "str" },
      { name: "Survival", value: 1, defaultAttribute: "end" },
      { name: "Repair", value: 1, defaultAttribute: "int" },
      { name: "Unarmed", value: 2, defaultAttribute: "str" },
    ],
    items: [
      { kind: "apparel", name: "Drifter Outfit", physical: 1, energy: 2, locations: ["armL", "armR", "legL", "legR", "torso"], equipped: true },
      { kind: "weapon", name: "10mm Auto Pistol", attribute: "agi", skill: "smallGuns", weaponType: "smallGuns", damage: 3, damageType: "physical", range: "close", fireRate: 4, qualities: ["close_quarters", "inaccurate"], damageEffects: [{ key: "burst", value: 1 }] },
      { kind: "ability", name: "Let Rip", description: "Once per combat, the merchant may add the 10mm auto pistol's Fire Rate to the weapon's damage and use Burst without spending extra ammo." },
      { kind: "ability", name: "Master Trader", description: "The merchant gains one automatic success on opposed Barter tests in addition to any rolled successes." },
      { kind: "ability", name: "Shopkeep", description: "The merchant is running a shop and typically has 6d20 caps available for trade." },
    ],
    biography: "Generic Diamond City merchant chassis usable for Vadim, Percy, and other trade-facing NPCs in the booklet.",
  },
  {
    name: "Miss Nanny Clara",
    type: "robot",
    category: "notable",
    xp: 90,
    level: 6,
    token: "systems/fallout/assets/tokens/robot.webp",
    special: { str: 6, per: 7, end: 5, cha: 5, int: 7, agi: 6, luc: 4 },
    derived: { hp: 15, initiative: 15, defense: 1, carryWeight: 150, meleeBonus: 0, luck: 2 },
    bodyResist: {
      physical: { head: 1, torso: 1, armL: 1, armR: 1, legL: 1, legR: 1 },
      energy: { head: 1, torso: 1, armL: 1, armR: 1, legL: 1, legR: 1 },
    },
    immunities: { poison: true, radiation: true },
    skills: [
      { name: "Energy Weapons", value: 3, tag: true, defaultAttribute: "per" },
      { name: "Repair", value: 1, defaultAttribute: "int" },
      { name: "Medicine", value: 4, tag: true, defaultAttribute: "int" },
      { name: "Small Guns", value: 1, defaultAttribute: "agi" },
      { name: "Melee Weapons", value: 3, tag: true, defaultAttribute: "str" },
      { name: "Speech", value: 1, defaultAttribute: "cha" },
    ],
    items: [
      { kind: "weapon", name: "Pincer", attribute: "str", skill: "meleeWeapons", weaponType: "meleeWeapons", damage: 3, damageType: "physical", range: "close", melee: true, natural: true },
      { kind: "weapon", name: "Buzzsaw", attribute: "str", skill: "meleeWeapons", weaponType: "meleeWeapons", damage: 3, damageType: "physical", range: "close", melee: true, natural: true, damageEffects: [{ key: "piercing_x", value: 1 }] },
      { kind: "weapon", name: "Flamer", attribute: "per", skill: "energyWeapons", weaponType: "energyWeapons", damage: 3, damageType: "energy", range: "close", fireRate: 1, damageEffects: [{ key: "persistent", value: 1 }] },
      { kind: "ability", name: "Robot", description: "Immune to starvation, thirst, suffocation, poison, and radiation; repairs instead of medical healing." },
      { kind: "ability", name: "Immune to Poison", description: "The Miss Nanny reduces poison damage suffered to 0 and cannot suffer poison effects." },
      { kind: "ability", name: "Immune to Radiation", description: "The Miss Nanny reduces radiation damage suffered to 0 and cannot suffer radiation effects." },
      { kind: "ability", name: "Immune to Disease", description: "The Miss Nanny ignores the effects of disease." },
      { kind: "ability", name: "Miss Nanny", description: "360° senses, airborne movement, and improved detection for visual and olfactory PER tests." },
    ],
    biography: "Mika's modified Miss Nanny guardian, equal parts interrogator, medic, and flamethrower platform.",
  },
  {
    name: "Synth Replica",
    type: "creature",
    category: "normal",
    xp: 31,
    level: 4,
    token: "systems/fallout/assets/tokens/npc.webp",
    creature: { body: 6, mind: 5, melee: 2, guns: 2, other: 2 },
    derived: { hp: 10, initiative: 11, defense: 1 },
    creatureResist: { physical: 2, energy: 3, radiation: 0, poison: 0 },
    creatureLocationText: {
      physical: "Head, Legs, Arms 2; Torso 1",
      energy: "Head, Legs, Arms 3; Torso 2",
      poison: "Immune",
      radiation: "Immune",
    },
    immunities: { poison: true, radiation: true },
    items: [
      { kind: "weapon", name: "Auto Pipe Gun", creatureAttribute: "body", creatureSkill: "guns", weaponType: "smallGuns", damage: 2, damageType: "physical", range: "medium", fireRate: 4, qualities: ["two_handed", "unreliable"], damageEffects: [{ key: "burst", value: 1 }] },
      { kind: "weapon", name: "Shock Baton", creatureAttribute: "body", creatureSkill: "melee", weaponType: "meleeWeapons", damage: 5, damageType: "energy", range: "close", melee: true },
      { kind: "ability", name: "Robot", description: "The synth is immune to starvation, thirst, suffocation, poison, and radiation, but does not heal naturally and must be repaired instead of treated with Medicine." },
      { kind: "ability", name: "Immune to Fear", description: "The synth cannot be intimidated or threatened and ignores most attempts to cow it." },
      { kind: "ability", name: "Immune to Disease", description: "The synth ignores the effects of disease." },
      { kind: "ability", name: "Third-Generation Synth", description: "The synth can pass as human until its synth component is recovered after death, and gains a bonus when impersonating a known individual." },
    ],
    biography: "Generation 3 synth enforcer profile for the finale bunker ambush.",
  },
];

export const STORY_NPC_PAGES = [
  {
    title: "Story NPCs",
    html: `
<h2>Mika</h2>
<p>Mika is a brilliant ecologist and vault dweller from a little-known vault far to the west. Her community is starving as key systems fail, and she crossed the Commonwealth with a G.E.C.K. hoping to find a safe place to use it and save her people.</p>
<p>She is dying by the time the party finds her in Vault 95. She only fully opens up to people who show empathy, and her last request is that the party find Clements in Diamond City and tell him it is time to find the Promised Land.</p>
<h2>Clements</h2>
<p>Clements is an older scavenger and carpenter helping build the All Faiths Chapel in Diamond City. He became one of Mika's few trusted friends after protecting her from a synth impostor, and he knows the route to Mika's bunker beneath the city.</p>
<p>He reacts strongly to news of Mika's death but can become a key ally if the party seems committed to using the G.E.C.K. well. If they come off selfish or reckless, mark that distrust for the finale and any follow-up play.</p>
<h2>Diamond City Contacts</h2>
<p>Travis Miles is worried about Mika but knows little beyond her paranoia and connection to Clements. Simon at Chem-I-Care remembers Mika as a regular Mentats buyer. Vadim Bobrov knows more than he admits and secretly helped Mika use the Dugout Inn tunnel. Percy and Takahashi are useful local color and shop anchors rather than major plot movers.</p>
`,
  },
  {
    title: "Encounter Roster",
    html: `
<p>Use the actor compendium as your ready rack while running the module.</p>
<ul>
  <li>Vault 95 opening: Rad Rocky, Raider, Doctor Rast (Vault Escort), Mister Gutsy</li>
  <li>Road and ruins: Dog, Feral Ghoul, Mirelurk Hatchling, Mirelurk Queen, Wounded, Super Mutant</li>
  <li>Diamond City and finale: Diamond City Security, Commonwealth Merchant, Miss Nanny Clara, Synth Replica, Doctor Rast (Finale)</li>
</ul>
<p>The merchant profile is intentionally generic so it can stand in for multiple Diamond City traders when a scene needs a full stat block fast.</p>
`,
  },
];
